# Site settings
title: Singing To Save Leith Hill
header-img: img/banner.jpg
email: sing@voiceforleithhill.co.uk
copyright_name:
description: "Community blues band protesting against the proposed oil exploration at Leith Hill"
baseurl: ""
url: "http://www.leithhillblues.co.uk"
twitter_username:
github_username:
facebook_username:
email_username:
port: 4002

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-84292677-2

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap]
